export const MockData = [
  {
    name: '☕️ Café da Manhã',
    time: '05:30',
    options: [
      {
        name: 'Opção 1',
        items: [
          {
            name: 'Ovos (2)',
            calories: 140,
            quantity: '2 unidades',
            protein: 12,
            carbs: 1,
            fat: 10,
          },
          {
            name: 'Aveia (40g)',
            calories: 150,
            quantity: '40g',
            protein: 5,
            carbs: 27,
            fat: 2,
          },
          {
            name: 'Banana',
            calories: 105,
            quantity: '1 unidade',
            protein: 1.3,
            carbs: 27,
            fat: 0.3,
          },
        ],
      },
      {
        name: 'Opção 2',
        items: [
          {
            name: 'Iogurte desnatado (150g)',
            calories: 70,
            quantity: '150g',
            protein: 10,
            carbs: 10,
            fat: 0.5,
          },
          {
            name: 'Frutas vermelhas (100g)',
            calories: 40,
            quantity: '100g',
            protein: 1,
            carbs: 10,
            fat: 0.1,
          },
          {
            name: 'Aveia (30g)',
            calories: 110,
            quantity: '30g',
            protein: 4,
            carbs: 20,
            fat: 1,
          },
        ],
      },
      {
        name: 'Opção 3',
        items: [
          {
            name: 'Queijo cottage (100g)',
            calories: 100,
            quantity: '100g',
            protein: 25,
            carbs: 3,
            fat: 1,
          },
          {
            name: 'Pedaços de mamão (150g)',
            calories: 60,
            quantity: '150g',
            protein: 1,
            carbs: 15,
            fat: 0.2,
          },
          {
            name: 'Torrada integral (1 fatia)',
            calories: 70,
            quantity: '1 fatia',
            protein: 4,
            carbs: 12,
            fat: 1,
          },
        ],
      },
    ],
  },
  {
    name: '🍏 Lanche da Manhã',
    time: '08:30',
    options: [
      {
        name: 'Opção 1',
        items: [
          {
            name: 'Whey Protein (30g)',
            calories: 120,
            quantity: '30g',
            protein: 24,
            carbs: 3,
            fat: 1,
          },
          {
            name: 'Maçã',
            calories: 95,
            quantity: '1 unidade',
            protein: 0.5,
            carbs: 25,
            fat: 0.3,
          },
        ],
      },
      {
        name: 'Opção 2',
        items: [
          {
            name: 'Sanduíche de frango (peito)',
            calories: 250,
            quantity: '1 unidade',
            protein: 30,
            carbs: 20,
            fat: 8,
          },
          {
            name: 'Laranja',
            calories: 60,
            quantity: '1 unidade',
            protein: 1,
            carbs: 15,
            fat: 0.1,
          },
        ],
      },
      {
        name: 'Opção 3',
        items: [
          {
            name: 'Rap10 com frango (peito) e salada',
            calories: 200,
            quantity: '1 unidade',
            protein: 25,
            carbs: 15,
            fat: 5,
          },
          {
            name: 'Morango (100g)',
            calories: 30,
            quantity: '100g',
            protein: 1,
            carbs: 8,
            fat: 0,
          },
        ],
      },
    ],
  },
  {
    name: '🥗 Almoço',
    time: '12:00',
    options: [
      {
        name: 'Opção 1',
        items: [
          {
            name: 'Arroz integral (100g)',
            calories: 110,
            quantity: '100g',
            protein: 2,
            carbs: 22,
            fat: 1,
          },
          {
            name: 'Feijão (100g)',
            calories: 120,
            quantity: '100g',
            protein: 7,
            carbs: 20,
            fat: 1,
          },
          {
            name: 'Frango grelhado (150g)',
            calories: 200,
            quantity: '150g',
            protein: 30,
            carbs: 0,
            fat: 5,
          },
          {
            name: 'Salada verde',
            calories: 20,
            quantity: '1 concha',
            protein: 1,
            carbs: 3,
            fat: 0,
          },
        ],
      },
      {
        name: 'Opção 2',
        items: [
          {
            name: 'Peixe grelhado (150g)',
            calories: 180,
            quantity: '150g',
            protein: 30,
            carbs: 0,
            fat: 7,
          },
          {
            name: 'Batata doce assada (100g)',
            calories: 100,
            quantity: '100g',
            protein: 2,
            carbs: 22,
            fat: 0,
          },
          {
            name: 'Couve cozida',
            calories: 20,
            quantity: '1 concha',
            protein: 1,
            carbs: 3,
            fat: 0,
          },
        ],
      },
      {
        name: 'Opção 3',
        items: [
          {
            name: 'Lentilha (100g)',
            calories: 116,
            quantity: '100g',
            protein: 9,
            carbs: 20,
            fat: 1,
          },
          {
            name: 'Carne magra (150g)',
            calories: 200,
            quantity: '150g',
            protein: 30,
            carbs: 0,
            fat: 7,
          },
          {
            name: 'Salada mista',
            calories: 30,
            quantity: '1 concha',
            protein: 1,
            carbs: 5,
            fat: 0,
          },
        ],
      },
    ],
  },
  {
    name: '🥪 Lanche da Tarde',
    time: '15:00',
    options: [
      {
        name: 'Opção 1',
        items: [
          {
            name: 'Whey Protein (30g)',
            calories: 120,
            quantity: '30g',
            protein: 24,
            carbs: 3,
            fat: 1,
          },
          {
            name: 'Uva (100g)',
            calories: 40,
            quantity: '100g',
            protein: 0,
            carbs: 10,
            fat: 0,
          },
        ],
      },
      {
        name: 'Opção 2',
        items: [
          {
            name: 'Sanduíche de frango (peito) light',
            calories: 180,
            quantity: '1 unidade',
            protein: 20,
            carbs: 10,
            fat: 5,
          },
          {
            name: 'Pêssego',
            calories: 60,
            quantity: '1 unidade',
            protein: 1,
            carbs: 15,
            fat: 0,
          },
        ],
      },
      {
        name: 'Opção 3',
        items: [
          {
            name: 'Crepioca com queijo magro',
            calories: 150,
            quantity: '1 unidade',
            protein: 15,
            carbs: 10,
            fat: 5,
          },
          {
            name: 'Abacaxi (100g)',
            calories: 50,
            quantity: '100g',
            protein: 0.5,
            carbs: 13,
            fat: 0,
          },
        ],
      },
    ],
  },
  {
    name: '🍗 Jantar',
    time: '19:00',
    options: [
      {
        name: 'Opção 1',
        items: [
          {
            name: 'Salada de folhas verdes com tomate e frango grelhado (100g)',
            calories: 120,
            quantity: '1 prato',
            protein: 20,
            carbs: 5,
            fat: 4,
          },
          {
            name: 'Bis (1 unidade)',
            calories: 31,
            quantity: '1 unidade',
            protein: 0.5,
            carbs: 6,
            fat: 1,
          },
        ],
      },
      {
        name: 'Opção 2',
        items: [
          {
            name: 'Peixe branco grelhado (100g)',
            calories: 100,
            quantity: '100g',
            protein: 20,
            carbs: 0,
            fat: 3,
          },
          {
            name: 'Sopa de legumes (1 prato)',
            calories: 80,
            quantity: '1 prato',
            protein: 3,
            carbs: 15,
            fat: 1,
          },
          {
            name: 'Bis (1 unidade)',
            calories: 31,
            quantity: '1 unidade',
            protein: 0.5,
            carbs: 6,
            fat: 1,
          },
        ],
      },
      {
        name: 'Opção 3',
        items: [
          {
            name: 'Omelete de claras com espinafre (2)',
            calories: 100,
            quantity: '2 unidades',
            protein: 16,
            carbs: 2,
            fat: 3,
          },
          {
            name: 'Salada de tomate e pepino',
            calories: 20,
            quantity: '1 concha',
            protein: 1,
            carbs: 3,
            fat: 0,
          },
          {
            name: 'Bis (1 unidade)',
            calories: 31,
            quantity: '1 unidade',
            protein: 0.5,
            carbs: 6,
            fat: 1,
          },
        ],
      },
    ],
  },
];
